# The numpy array

In [30]:
import numpy as np

### Create N dimensional arrays:

By literal - note that the number of opening squares equals the dimension

In [31]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

Create array filled with random values: __np.empty__ of type __np.int8__

In [32]:
b = np.empty( (3,2), dtype=np.int8  )
b

array([[-120,   -5],
       [  53, -124],
       [  54,  127]], dtype=int8)

Create array by __np.arange()__ method (quite simmilar to python's __range()__)

In [33]:
b = np.arange(0,21,2)
b

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### Simple indexing

In [34]:
a[1,2]

6

**Note: index chaining returns the same result, but is more inefficient as a new temporary array is created after the first index that is subsequently indexed by 2.**

In [35]:
# not efficient
a[1][2]

6

### Basic numpy properties and methods

The number of axes (dimensions) of the array: __a.ndim__

In [36]:
a = np.array([[1,2,3],[4,5,6]])
a.ndim

2

Tuple of integers indicating the size of the array in each dimension: __ndarray.shape__

In [37]:
a = np.array([[1,2,4],[4,5,6]])
a.shape

(2, 3)

In [38]:
b = np.array([[1,2],[3,4],[5,6]])
b.shape

(3, 2)

Total number of elements of the array: __a.size__

In [39]:
a = np.array([[1,2,3],[4,5,6]])
a.size

6

The size in bytes of each element of the array: __a.itemsize__

In [40]:
a = np.array([[1,2,3],[4,5,6]])
a.itemsize

8

### Array Manipulations

##### Flatten the array

In [41]:
a = np.array([[1,2,3],[4,5,6]])
a.ravel()

array([1, 2, 3, 4, 5, 6])

#### reshaping arrays: __np.reshape()__

In [42]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
a.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
a.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

### Arrays Algebra (Element Wise)

In [45]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6]])

a+b

array([[ 2,  4,  6],
       [ 8, 10, 12]])

#### matrix product: __dot()__ 

In [46]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2],[3,4],[5,6]])

a.dot(b)

array([[22, 28],
       [49, 64]])

In [47]:
b.dot(a)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])